export {
  GlobalRole,
  InstitutionRole,
  QuestionType,
  ExamStatus,
  EnrollmentStatus,
  AccommodationType,
  FlagType,
  ReviewStatus,
  ViolationType,
  ResultStatus,
  ReEvalStatus,
  AccommodationAction,
  NotificationType,
} from "@prisma/client";
